name: Deploy Docusaurus site to GitHub Pages

on:
  push:
    branches:
      - master  # Adjust if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Ensure Node.js version is 18 or higher

    - name: Install dependencies
      run: npm install
      working-directory: ./docs

    - name: Build Docusaurus site
      run: npm run build
      working-directory: ./docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        publish_dir: ./docs/build
        external_repository: jpranays/react-fast-hooks  # Ensure this is your repo name
        force_orphan: true
